/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espoch.wckm2025.Vista;

import ec.edu.espoch.wckm2025.Modelo.GestorTareas;
import java.awt.event.ActionEvent;
import javax.swing.*;


/**
 *
 * @author USER
 */
public class vista extends javax.swing.JFrame {
        private GestorTareas gestorTareas;

    public vista(GestorTareas gestor) {
        this.gestorTareas = gestor;
        initComponents();
    }
  @SuppressWarnings("unchecked")
    private void initComponents() {

        escritorio = new JDesktopPane();
        jMenuBar1 = new JMenuBar();
        mnMenu = new JMenu();
        mntAgregarTarea = new JMenuItem();
        mntListarPendientes = new JMenuItem();
        mntListarCompletas = new JMenuItem();
        mntSalir = new JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Tareas");

        mnMenu.setText("Menú");
    /**
     * Creates new form vista
     */
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        lblTitulo = new javax.swing.JLabel();
        lblIngreseTitulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaDescripcion = new javax.swing.JTextArea();
        lblDescripcion = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnMenu = new javax.swing.JMenu();
        mntAgregarTarea = new javax.swing.JMenuItem();
        mntListarPendientes = new javax.swing.JMenuItem();
        mntListarCompletas = new javax.swing.JMenuItem();
        mntSalir = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("GESTOR DE TAREAS ");

        lblIngreseTitulo.setText("Ingrese el titulo de la tarea");

        txtaDescripcion.setColumns(20);
        txtaDescripcion.setRows(5);
        jScrollPane2.setViewportView(txtaDescripcion);

        lblDescripcion.setText("Descripcion");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        escritorio.setLayer(lblTitulo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(lblIngreseTitulo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(lblDescripcion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblIngreseTitulo))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(lblDescripcion)))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(lblTitulo))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jButton1)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(41, 41, 41)
                .addComponent(lblIngreseTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescripcion))
                .addGap(57, 57, 57)
                .addComponent(jButton1)
                .addGap(7, 7, 7))
        );

        mnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espoch/wckm2025/Vista/iconos/pngwing.com (3).png"))); // NOI18N
        mnMenu.setText("Menu");
        mnMenu.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        mnMenu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnMenuActionPerformed(evt);
            }
        });

        mntAgregarTarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espoch/wckm2025/Vista/iconos/pngwing.com (4).png"))); // NOI18N
        mntAgregarTarea.setText("Agregar Tarea nueva");
        mntAgregarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntAgregarTareaActionPerformed(evt);
            }
        });
        mnMenu.add(mntAgregarTarea);

        mntListarPendientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espoch/wckm2025/Vista/iconos/pngwing.com (5).png"))); // NOI18N
        mntListarPendientes.setText("Listar tareas pendientes");
        mntListarPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntListarPendientesActionPerformed(evt);
            }
        });
        mnMenu.add(mntListarPendientes);

        mntListarCompletas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espoch/wckm2025/Vista/iconos/pngwing.com (6).png"))); // NOI18N
        mntListarCompletas.setText("Listar tareas completadas ");
        mntListarCompletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntListarCompletasActionPerformed(evt);
            }
        });
        mnMenu.add(mntListarCompletas);

        mntSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espoch/wckm2025/Vista/iconos/pngwing.com (7).png"))); // NOI18N
        mntSalir.setText("Salir");
        mntSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntSalirActionPerformed(evt);
            }
        });
        mnMenu.add(mntSalir);

        jMenuBar1.add(mnMenu);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espoch/wckm2025/Vista/iconos/pngwing.com (7).png"))); // NOI18N
        jMenu1.setText("Cerrar");
        jMenu1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mntListarCompletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntListarCompletasActionPerformed
          mntListarCompletas.setText("Listar tareas completadas");
        mntListarCompletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntListarCompletasActionPerformed(evt);
            }
        });
        mnMenu.add(mntListarCompletas);
    }//GEN-LAST:event_mntListarCompletasActionPerformed

    private void mntListarPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntListarPendientesActionPerformed
   mntListarPendientes.setText("Listar tareas pendientes");
        mntListarPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntListarPendientesActionPerformed(evt);
            }
        });
        mnMenu.add(mntListarPendientes);
      
    }//GEN-LAST:event_mntListarPendientesActionPerformed
   
    private void mntSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntSalirActionPerformed
            
        System.exit(0);
    }//GEN-LAST:event_mntSalirActionPerformed

    private void mnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnMenuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

       
   
    private void mntAgregarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntAgregarTareaActionPerformed
   mntAgregarTarea.setText("Agregar nueva tarea");
        mntAgregarTarea.addActionListener(new java.awt.event.ActionListener() {
       @Override
       public void actionPerformed(ActionEvent e) {
           throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
       }
            
        });
        mnMenu.add(mntAgregarTarea);

    }//GEN-LAST:event_mntAgregarTareaActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblIngreseTitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenu mnMenu;
    private javax.swing.JMenuItem mntAgregarTarea;
    private javax.swing.JMenuItem mntListarCompletas;
    private javax.swing.JMenuItem mntListarPendientes;
    private javax.swing.JMenuItem mntSalir;
    private javax.swing.JTextArea txtaDescripcion;
    // End of variables declaration//GEN-END:variables
}
}